Opportunity to change admin accounts
pontem-network/liquidswap pull request #93
Opened 2022-09-19 15:20 UTC by sunmoon11100

2022-09-22 23:42 UTC, mkurnikov requested changes

2022-09-22 23:42 UTC, mkurnikov commented on sources/swap/config.move
> +    const MAX_DAO_FEE: u64 = 100;
Now you have duplicated set of constants? The same ones are present in `liquidity_pool.move`

2022-09-22 23:42 UTC, mkurnikov commented on sources/swap/config.move
> +    const MAX_DAO_FEE: u64 = 100;
Add `is_valid_fee` and `is_valid_dao_fee` functions.

2022-09-22 23:42 UTC, mkurnikov commented on sources/swap/config.move
> +            default_dao_fee: 33,
Add comments that it's 0.3%, 0.04% and 33%

2022-09-23 16:34 UTC, borispovod approved these changes
Well, let's merge all together and after i will share opinion.
Currently i see minor issues in this branch, probably fixed in `dynamic-fees`.

2022-09-23 16:35 UTC, merged